### ISSUE TITLE
Couldn't get it to work

### ISSUE THREAD

**Issue by WolfgangFahl** [di/flask-accept#11]
see https://stackoverflow.com/questions/28791613/route-requests-based-on-the-accept-header-in-flask/47838604#47838604

why i tried this.

after having put:
```
# Content negotiation
# https://pypi.org/project/flask_accept/
flask_accept
```
in my requirements.txt and install thing with pip the example import
from flask_accept import accept did not work - showed and error in my IDE liclipse that the import was not available.
```
python --version
Python 3.6.10
...
pip 20.0.2

```

`pip uninstall flask_accept
Found existing installation: flask-accept 0.0.6
Uninstalling flask-accept-0.0.6:
  Would remove:
    /Users/wf/Library/Python/3.7/lib/python/site-packages/flask_accept-0.0.6.dist-info/*
    /Users/wf/Library/Python/3.7/lib/python/site-packages/flask_accept/*
Proceed (y/n)? y
  Successfully uninstalled flask-accept-0.0.6`

will downvote the answer now and try another option until it's clear what is going on

**Comment by di** [comment]
Sorry, there's not enough information here. What error did you get when you tried to do `from flask_accept import accept`?

**Comment by WolfgangFahl** [comment]
thx for the swift reply - so let's go again

```
./install  | grep flask
Requirement already satisfied: flask_accept in /private/var/root/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 29)) (0.0.6)
```
auto completion in Eclipse/Liclipse doesn't offer flask accept after refreshing the project:
![auto-completion](https://user-images.githubusercontent.com/1336221/87173123-8eede780-c2d5-11ea-8371-1fe4d9b54fd7.png)

unresolved import:
![grafik](https://user-images.githubusercontent.com/1336221/87173499-26ebd100-c2d6-11ea-9eb4-089d53864bfe.png)


running from command line:

```
Traceback (most recent call last):
  File "ptp/webserver.py", line 10, in <module>
    from flask_accept import accept
ModuleNotFoundError: No module named 'flask_accept'
```

**Comment by di** [comment]
You mentioned Python 3.6.10 in the first comment, but this says it's installed for Python 3.7:

```
Requirement already satisfied: flask_accept in /private/var/root/Library/Python/3.7/lib/python/site-packages (from -r requirements.txt (line 29)) (0.0.6)
```

Which Python version are you actually using?

**Comment by WolfgangFahl** [comment]
You are right. It's one of the reasons i work with scripts:

`python3 --version
Python 3.7.7`

The whole project is available at https://github.com/WolfgangFahl/ProceedingsTitleParser - I'll check in the version i suspect is not working so that travis will try it's think and might not work in multiple python versions - let's see.

**Comment by WolfgangFahl** [comment]
I'd like to implement https://github.com/WolfgangFahl/ProceedingsTitleParser/issues/20

**Comment by WolfgangFahl** [comment]
There is now a [specific commit](https://github.com/WolfgangFahl/ProceedingsTitleParser/commit/c2134c302bd0be78a4a0bc086bf66e149de7f244) for this issue:

The local test result in the MacOSX / Macports environment is:
```./test

ERROR: tests.test_WebServer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_WebServer
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/wf/Documents/pyworkspace/ProceedingsTitleParser/tests/test_WebServer.py", line 8, in <module>
    from ptp.webserver import app
  File "/Users/wf/Documents/pyworkspace/ProceedingsTitleParser/ptp/webserver.py", line 14, in <module>
    from flask_accept import accept
ModuleNotFoundError: No module named 'flask_accept'

```

while https://travis-ci.org/github/WolfgangFahl/ProceedingsTitleParser/jobs/707146166 looks just fine 
```
cat .travis.yml 
dist: bionic
# see https://docs.travis-ci.com/user/languages/python/
language: python
# python versions to be tested
python:
#  - "2.7" # see https://github.com/WolfgangFahl/gremlin-python-tutorial/issues/7
  - "3.6"
  - "3.7"
  - "3.8"
# allow gui output
services:
  - xvfb
before_install:
  # install some renderers
  # check version
  - lsb_release -a
install:
  - echo $USER
# command to run tests
script:
# command to install dependencies
  - ./install
# command to get sample data
  - ./getsamples
# command to run tests
  - ./test
```
So the issue might be operating system / environment specific.

**Comment by di** [comment]
I think this is probably an issue with your local environment. I'm also on macOS and can install/use this library just fine.

Can you give me specific steps to reproduce after cloning your repo?

**Comment by WolfgangFahl** [comment]
@di thx for staying tuned. Since I suspect the environment issue i did the following on another comparable server:
```
sudo port self update
sudo port self upgrade outdated
sudo port select --set python python38
sudo port select --set python3 python38
sudo port install py38-pip
sudo port select --set pip pip38
sudo port select --set pip3 pip38
python --version
Python 3.8.3
python3 --version
Python 3.8.3
pip --version
pip 20.1.1 from /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)
pip3 --version
pip 20.1.1 from /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)
```

Then the test and installation procedure is pretty straight forward see http://wiki.bitplan.com/index.php/ProceedingsTitleParser#Installation.

Getting the samples might take a few minutes  and will need 60 MBytes of disk space. The git rep itself is not too big. I'll share my results in a few minutes.

**Comment by WolfgangFahl** [comment]
It's grand i get
```
./test 2>&1 | grep "No module"
ModuleNotFoundError: No module named 'yaml'
ModuleNotFoundError: No module named 'yaml'
ModuleNotFoundError: No module named 'yaml'
ModuleNotFoundError: No module named 'wikibot'
ModuleNotFoundError: No module named 'matplotlib'
ModuleNotFoundError: No module named 'pyparsing'
ModuleNotFoundError: No module named 'yaml'
ModuleNotFoundError: No module named 'flask'
```
So it's definitely not the library but the python/pip setup ... Still it'd appreciate to get this puzzle solved ...

**Comment by WolfgangFahl** [comment]
sudo -H pip3 seems to be the culprit. I had this recommended somewhere and was using it for a few month and now it seems to fail badly.

**Comment by WolfgangFahl** [comment]
Eclipse / Liclipse still does not like this solution. For the time being i am sticking to
`if request.accept_mimetypes['application/json']:
`
and

`      response = Response(status=200,mimetype='application/json')
`

**Comment by WolfgangFahl** [comment]
I have now followed the Macports Upgrade procedure to 3.8 on my machine, rebooted it and restarted Eclipse. I was asked whether i'd like to update my environment to 3.8 and now things seem to work. Thx.
