### ISSUE TITLE
How to return the default response with mime 'application/json' instead of 'text/html'

### ISSUE THREAD

**Issue by TapanHP1995** [di/flask-accept#12]
The response in every case is always 'text/html' like this

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>406 Not Acceptable</title>
<h1>Not Acceptable</h1>
<p>The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request. Supported entities are: application/json</p>
```

Is there any way to send a response in 'application/json' format automatically?

**Comment by di** [comment]
Hi, can you provide a minimal example?

**Comment by TapanHP1995** [comment]
Here is where I created a function and defined the @accept decorator

```
@accept("application/json")
@demo_bp.route('/server_check', methods=['GET'])
def check_server_health():
    """
    This method is just for checking server health and endpoints working
    :return: A simple string message
    """
    return send_success_response(message="Server is working OK")
```

When I can  this endpoint from postman or cUrl with let's say "text/html" then It will send me error in HTML format, as I think you have raised `NotAcceptable` exception in code

So it will show,

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>406 Not Acceptable</title>
<h1>Not Acceptable</h1>
<p>The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request. Supported entities are: application/json</p>
```

Now If I want the response in JSON in this case as I am using it with APIs so front end will expect to be it in Json with maybe a response like this one.

`{error: "The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request. Supported entities are: application/json"}`

Can I do it, or it will be always in HTML?

**Comment by di** [comment]
OK, so here's an actual minimal example:

```python
from flask import Flask, jsonify

from flask_accept import accept

app = Flask(__name__)

@app.route('/', methods=['GET'])
@accept("application/json")
def check():
    return "Server is working OK"

app.run('0.0.0.0', 8080, debug=True)
```

If I run this locally, I get:

```
$ curl localhost:8080
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>406 Not Acceptable</title>
<h1>Not Acceptable</h1>
<p>The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request. Supported entities are: application/json</p>
```

To make that a JSON response instead, you need to provide a custom error handler, for example:

```python
from flask import jsonify

@app.errorhandler(406)
def not_acceptable(e):
    return jsonify({'error': 'Not Acceptable'}), 406
```

Which will give you:

```
$ curl localhost:8080
{
  "error": "Not Acceptable"
}
```

**Comment by TapanHP1995** [comment]
So How would the library fit in this case? So in your example, the accept decorator is not added. So I am confused about how it will work? so let's say using the library instead of sending the HTML response. What I intended to do is 

`{"message": "The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request. Supported entities are: application/json"}`

using the accept library itself and not adding one more error handler, In your JSON example you have not used the library at all

**Comment by di** [comment]
I think you need to take a closer look at the example 🙂

**Comment by TapanHP1995** [comment]
okay so If I override the 406 at app handler level then accept would automatically follow what that function is sending, right?

**Comment by di** [comment]
Yes.
